# Generated by Django 5.2.8 on 2026-03-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_datacollectionrecord_agent_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datacollectionrecord",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
    ]
