# Generated by Django 5.2.8 on 2026-03-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_datacollectionrecord_rejection_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="datacollectionrecord",
            name="latitude",
            field=models.FloatField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name="datacollectionrecord",
            name="longitude",
            field=models.FloatField(null=True, blank=True),
        ),
    ]
