# Generated by Django 5.2.8 on 2026-03-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_datacollectionrecord_lat_lng"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="daily_target",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="user",
            name="national_id",
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
